[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-{GENERATED_NONCE}'; style-src 'self'; img-src 'self' data: https://images.ctfassets.net; font-src 'self' data:; connect-src 'self'; media-src 'self'; object-src 'none'; frame-ancestors 'none'; block-all-mixed-content"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
